#!/bin/bash

# SVTGet v0.1.1
# Updates can be found at http://svtget.se/
# Support the project with Flattr: https://flattr.com/thing/300374/SVT-Get-a-local-cache-tool-for-SVT-Play
#
# Description: The script can download the RTMP streams available from the
# online streaming service "SVT Play", managed by Sveriges Television
#
# Original author: Mikael "MMN-o" Nordfeldth
# License: GPLv3
# http://www.gnu.org/licenses/gpl-3.0.txt
#
# URL: http://blog.mmn-o.se/
# Flattr: https://flattr.com/thing/188162/MMN-o-on-Flattr

# Changelog:
# -- v0.1.1
#    * deb package created by sikevux, small fixes on other stuff
# -- v0.1
#    * Initial functionality. Normal links seem to be working.

# Sample usage:
# ./svtget http://svtplay.se/v/2440756/k_special/presspauseplay

DEPENDENCIES="rtmpdump curl sed cut bash"
for DEP in $DEPENDENCIES; do
	if [ -z "`which $DEP`" ]; then
		echo "ERROR: Missing dependency '$DEP'." >&2
		exit
	fi
done

# Available bitrates: 320 850 1400 2400
BITRATE=""
function set_bitrate {
	case $1 in
	l)	BITRATE=320	;;
	m)	BITRATE=850	;;
	n)	BITRATE=1400	;;
	h)	BITRATE=2400	;;
	320|850|1400|2400)
		BITRATE=$1	;;
	*)
		echo "Bad quality setting ($1), keeping setting '$BITRATE'"
		;;
	esac
}

function get_tcUrl {
	local html=$1
	local bitrate=$2
	expr "$bitrate" + 1 &> /dev/null
	if [ $? -gt 0 ] || [ -z "$bitrate" ] || [ "$bitrate" -eq 0 ]; then
		bitrate='[0-9]\+'
	fi
	echo $html | sed "s/\(rtmp[e]\?:[^|&]*\),bitrate:\($bitrate\)/\\n\2|\1\\n/g" | grep -E '^[[:digit:]]+\|' | sort -n | uniq 
}

function pick_tcUrl {
	echo "#  Bitrate	Filename" >&2
	let n=1
	for STREAM in $@; do
		BITRATE=`echo $STREAM | cut -d '|' -f 1 -`
		Streams[$n]=`echo $STREAM | cut -d '|' -f 2 -`
		FILENAME=`basename $STREAM`
		echo "$n. ${BITRATE} kbps	$FILENAME" >&2
		let n++
	done
	
	stream=0
	if [ "$#" -eq 1 ]; then
		stream=1
	fi
	while [ -z ${Streams[$stream]} ]; do
		echo -ne "\nWhich file do you want? [#] "
		read stream
		if [ -n "$stream" ] && [ "q" == "$stream" ]; then
			exit
		fi
	done
	tcUrl=${Streams[$stream]}
}

while getopts "q:" opt; do
	case $opt in
	q)
		set_bitrate $OPTARG
		;;
	\?)
		echo "invalid option: -$OPTARG" >&2
		exit 1
		;;
	esac
done

pageUrl=${!#}
if [ -z "$pageUrl" ]; then
	echo "Usage: $0 [-q l|m|n|h] http://svtplay.se/v/..." >&2
	exit 1
fi

if [[ ! "$pageUrl" =~ http://svtplay.se ]]; then
	echo "Bad URL. Not SVT Play?" >&2
	exit 1
fi

HTML=`curl -s "$pageUrl"`
swfUrl="http://svtplay.se$(echo $HTML | sed 's/.*x-shockwave-flash" data="\([^"]\+\)\".*/\1/')"
echo $swfUrl
tcUrls=$(get_tcUrl "$HTML" "$BITRATE")
if [ -z "$tcUrls" ]; then
	echo "ERROR: No rtmp streams found. No clip in that quality?
Please visit http://svtget.se/ for updates and information. If the website's down, use a search engine to find copies." >&2
	exit 1
fi

pick_tcUrl $tcUrls

filename=`basename $tcUrl`
echo Running RTMPDump for "$tcUrl" and saving to "$filename"

rtmpdump -r "$tcUrl" --swfVfy="$swfUrl" -o "$filename"
