#!/bin/bash

# SVTGet v0.1.1
# Updates can be found at http://svtget.se/
# Support the project with Flattr: https://flattr.com/thing/300374/SVT-Get-a-local-cache-tool-for-SVT-Play
#
# Description: The script can download the RTMP streams available from the
# online streaming service "SVT Play", managed by Sveriges Television
#
# Original author: Mikael "MMN-o" Nordfeldth
# License: GPLv3
# http://www.gnu.org/licenses/gpl-3.0.txt
#
# URL: http://blog.mmn-o.se/
# Flattr: https://flattr.com/thing/188162/MMN-o-on-Flattr

# Changelog:
# -- v0.1.1
#    * deb package created by sikevux, small fixes on other stuff
# -- v0.1
#    * Initial functionality. Normal links seem to be working.

# Sample usage:
# ./svtget http://svtplay.se/v/2440756/k_special/presspauseplay

DEPENDENCIES="rtmpdump curl"
for DEP in $DEPENDENCIES; do
	if [ -z "`which $DEP`" ]; then
		echo "ERROR: Missing dependency '$DEP'."
		exit
	fi
done

if [ -z "$1" ]; then
	echo "Usage: $0 http://svtplay.se/v/..."
	exit 1
fi

if [[ ! "$1" =~ http://svt ]]; then
	echo "Bad URL. Not SVT Play?"
	exit
fi

SVTPLAY_HTML=`curl -s "$1"`
swfUrl="http://svtplay.se$(echo $SVTPLAY_HTML | grep 'application/x-shockwave-flash' | cut -d\" -f4)"
SVTGET_STREAMS=$(echo $SVTPLAY_HTML | sed "s/\(rtmp[e]\?:[^|&]*\),bitrate:\([0-9]\+\)/\n\2|\1\n/g" | grep rtmp | sort | uniq )

if [ -z "$SVTGET_STREAMS" ]; then
	echo "ERROR: No rtmp streams found. Website structure changed?"
	echo "Please visit http://svtget.se/ for updates and information. If the website's down, use a search engine to find copies."
	exit 1
fi

echo "#  Bitrate	Filename"
let n=1
for STREAM in $SVTGET_STREAMS; do
	BITRATE=`echo $STREAM | cut -d '|' -f 1 -`
	expr $BITRATE + 1 &> /dev/null
	if [ $? -gt 0 ] || [ "$BITRATE" -eq 0 ]; then
		continue
	fi
	URL=`echo $STREAM | cut -d '|' -f 2 -`
	FILENAME=`echo $STREAM | cut -d '/' -f8 -`
	echo "$n. ${BITRATE} kbps	$FILENAME"
	Streams[$n]="$URL"
	Filenames[$n]="$FILENAME"
	let n++
done

stream=0
while [ -z ${Streams[$stream]} ]; do
	echo ""
	echo -n "Which file do you want? [#] "
	read stream
	if [ -n "$stream" ] && [ "q" == "$stream" ]; then
		exit
	fi
done

echo Running RTMPDump for "${Streams[$stream]}" and saving to "${Filenames[$stream]}"

rtmpdump -r "${Streams[$stream]}" --swfVfy="$swfUrl" -o "${Filenames[$stream]}"
